name: run-tests

on: 
  workflow_call:
    outputs:
      pr_number:
        description: "The PR number"
        value: ${{ jobs.test.outputs.pr_number }}
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 'stable', 'oldstable', '1.20' ]
    name: Go ${{ matrix.version }}
    outputs:
      pr_number: ${{ github.event.number }}
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.version }}
    - uses: actions/checkout@v4
    - run: make test
  call-dependabot-pr-workflow:
    needs: test
    if: ${{ success() && github.actor == 'dependabot[bot]' }}
    uses: pivotal-cf/brokerapi/.github/workflows/dependabot-test.yml@main
    with:
      pr_number: ${{ github.event.number }}
